version: 2
updates:
    - package-ecosystem: "npm"
    # Keep npm dependencies up to date
      directory: "/"
    # Check the npm registry for updates at 2am UTC
      schedule:
        interval: "daily"
        time: "02:00"
    - package-ecosystem: "gitsubmodule"
    # Keep npm dependencies up to date
      directory: "/"
    # Check the npm registry for updates at 2am UTC
      schedule:
        interval: "daily"
        time: "02:00"
